//===============================================================
// File: ComparisonReportDocument.cs
// Author: Claude (Phase 10.5 - PDF Export)
// Date: 2025-11-15
// Purpose: QuestPDF document for single symbol comparison report.
//
// PHASE 10.5: PDF EXPORT - SINGLE COMPARISON REPORT
//   - Generates professional PDF report for comparison results
//   - Uses QuestPDF fluent API for declarative layout
//   - Embeds visual diff image from comparison
//   - Includes detailed statistics and metadata
//
// WHY THIS MATTERS:
//   - Students can save comparison results for assignments
//   - Instructors receive formatted reports for grading
//   - Demonstrates modern PDF generation with fluent API
//   - Creates professional artifacts from technical analysis
//
// TEACHING VALUE:
//   - Undergraduate: Document generation, layout design
//   - Graduate: QuestPDF fluent API patterns, image embedding
//   - PhD: Report design for academic submissions
//
// AUDIENCE: Undergraduate / Graduate (PDF generation)
//===============================================================
#nullable enable

using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SymbolLabsForge.UI.Web.Services;

namespace SymbolLabsForge.UI.Web.Documents
{
    /// <summary>
    /// QuestPDF document for single symbol comparison report.
    /// </summary>
    /// <remarks>
    /// <para><b>Phase 10.5: PDF Export with QuestPDF</b></para>
    /// <para>This document generates a Letter-size (8.5" × 11") PDF with:</para>
    /// <list type="number">
    /// <item>Header with "SymbolLabsForge Comparison Report" title</item>
    /// <item>Symbol metadata (type, timestamp, tolerance)</item>
    /// <item>Pass/Fail result with similarity percentage</item>
    /// <item>Detailed statistics table (pixels, errors, metrics)</item>
    /// <item>Visual diff image (embedded PNG)</item>
    /// <item>Footer with generation timestamp</item>
    /// </list>
    /// <para><b>Teaching Moment:</b> QuestPDF fluent API reads like natural language:</para>
    /// <code>
    /// column.Item().Text("Title").Bold().FontSize(20);
    /// column.Item().Image(imageBytes).FitWidth();
    /// </code>
    /// </remarks>
    public class ComparisonReportDocument : IDocument
    {
        private readonly ComparisonResult _result;
        private readonly SymbolType _symbolType;
        private readonly double _tolerance;
        private readonly byte[] _diffImageBytes;
        private readonly DateTime _generatedAt;

        public ComparisonReportDocument(
            ComparisonResult result,
            SymbolType symbolType,
            double tolerance,
            byte[] diffImageBytes)
        {
            _result = result;
            _symbolType = symbolType;
            _tolerance = tolerance;
            _diffImageBytes = diffImageBytes;
            _generatedAt = DateTime.UtcNow;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                // Page setup: Letter size (8.5" × 11"), portrait orientation
                page.Size(PageSizes.Letter);
                page.Margin(2); // 2 cm margin (default unit)
                page.DefaultTextStyle(x => x.FontSize(11));

                // Header section
                page.Header().Element(ComposeHeader);

                // Content sections
                page.Content().Column(column =>
                {
                    column.Spacing(10); // 10pt spacing between sections

                    // Section 1: Metadata
                    column.Item().Element(ComposeMetadata);

                    // Section 2: Result summary (pass/fail, similarity)
                    column.Item().Element(ComposeResultSummary);

                    // Section 3: Statistics table
                    if (_result.Statistics != null)
                    {
                        column.Item().Element(ComposeStatistics);
                    }

                    // Section 4: Visual diff image
                    column.Item().Element(ComposeVisualDiff);
                });

                // Footer section
                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by SymbolLabsForge on ");
                    text.Span(_generatedAt.ToString("yyyy-MM-dd HH:mm:ss UTC")).Italic();
                });
            });
        }

        /// <summary>
        /// Composes the header with title and branding.
        /// </summary>
        private void ComposeHeader(IContainer container)
        {
            container.Column(column =>
            {
                column.Item().Text("SymbolLabsForge")
                    .FontSize(20)
                    .Bold()
                    .FontColor(Colors.Blue.Darken3);

                column.Item().Text("Symbol Comparison Report")
                    .FontSize(16)
                    .SemiBold();

                column.Item().PaddingTop(5).BorderBottom(1).BorderColor(Colors.Grey.Lighten1);
            });
        }

        /// <summary>
        /// Composes the metadata section (symbol type, timestamp, tolerance).
        /// </summary>
        private void ComposeMetadata(IContainer container)
        {
            container.Column(column =>
            {
                column.Item().Text("Comparison Metadata").FontSize(14).SemiBold();

                column.Item().PaddingLeft(10).Column(innerColumn =>
                {
                    innerColumn.Item().Text(text =>
                    {
                        text.Span("Symbol Type: ").SemiBold();
                        text.Span(_symbolType.ToString());
                    });

                    innerColumn.Item().Text(text =>
                    {
                        text.Span("Tolerance: ").SemiBold();
                        text.Span($"{_tolerance:P2}"); // Format as percentage: 0.01 → 1.00%
                    });

                    innerColumn.Item().Text(text =>
                    {
                        text.Span("Comparison Date: ").SemiBold();
                        text.Span(_generatedAt.ToString("yyyy-MM-dd HH:mm:ss UTC"));
                    });
                });
            });
        }

        /// <summary>
        /// Composes the result summary (pass/fail status, similarity percentage).
        /// </summary>
        private void ComposeResultSummary(IContainer container)
        {
            container.Column(column =>
            {
                column.Item().Text("Comparison Result").FontSize(14).SemiBold();

                // Pass/Fail status with color coding
                column.Item().PaddingLeft(10).Text(text =>
                {
                    text.Span("Status: ").SemiBold();

                    if (_result.Similar)
                    {
                        text.Span("✅ PASS").FontColor(Colors.Green.Darken2).Bold();
                    }
                    else
                    {
                        text.Span("❌ FAIL").FontColor(Colors.Red.Darken2).Bold();
                    }
                });

                // Similarity percentage
                column.Item().PaddingLeft(10).Text(text =>
                {
                    text.Span("Similarity: ").SemiBold();
                    text.Span($"{_result.SimilarityPercent:F2}%");
                });

                // Difference percentage
                column.Item().PaddingLeft(10).Text(text =>
                {
                    text.Span("Difference: ").SemiBold();
                    text.Span($"{_result.DifferencePercent:F2}%");
                });

                // Error message (if present)
                if (!string.IsNullOrEmpty(_result.ErrorMessage))
                {
                    column.Item().PaddingLeft(10).PaddingTop(5)
                        .Background(Colors.Red.Lighten4)
                        .Padding(5)
                        .Text(_result.ErrorMessage)
                        .FontColor(Colors.Red.Darken3)
                        .Italic();
                }
            });
        }

        /// <summary>
        /// Composes the detailed statistics table.
        /// </summary>
        private void ComposeStatistics(IContainer container)
        {
            var stats = _result.Statistics!;

            container.Column(column =>
            {
                column.Item().Text("Detailed Statistics").FontSize(14).SemiBold();

                column.Item().PaddingLeft(10).Table(table =>
                {
                    // Define columns: Metric (60%) | Value (40%)
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(3); // Metric name
                        columns.RelativeColumn(2); // Value
                    });

                    // Header row
                    table.Header(header =>
                    {
                        header.Cell().Background(Colors.Grey.Lighten2).Padding(5)
                            .Text("Metric").SemiBold();
                        header.Cell().Background(Colors.Grey.Lighten2).Padding(5)
                            .Text("Value").SemiBold();
                    });

                    // Data rows
                    table.Cell().Padding(5).Text("Total Pixels");
                    table.Cell().Padding(5).Text(stats.TotalPixels.ToString("N0"));

                    table.Cell().Padding(5).Text("Different Pixels");
                    table.Cell().Padding(5).Text(stats.DifferentPixels.ToString("N0"));

                    table.Cell().Padding(5).Text("Max Error (0-255 scale)");
                    table.Cell().Padding(5).Text(stats.MaxError.ToString());

                    table.Cell().Padding(5).Text("Mean Error (average)");
                    table.Cell().Padding(5).Text($"{stats.MeanError:F2}");

                    table.Cell().Padding(5).Text("Similarity Percentage");
                    table.Cell().Padding(5).Text($"{stats.SimilarityPercent:F2}%");

                    table.Cell().Padding(5).Text("Difference Percentage");
                    table.Cell().Padding(5).Text($"{stats.DifferencePercent:F2}%");
                });
            });
        }

        /// <summary>
        /// Composes the visual diff image section.
        /// </summary>
        /// <remarks>
        /// <para><b>Teaching Moment:</b> QuestPDF embeds images directly from byte arrays.</para>
        /// <para>FitWidth() scales image to fit page width while maintaining aspect ratio.</para>
        /// </remarks>
        private void ComposeVisualDiff(IContainer container)
        {
            container.Column(column =>
            {
                column.Item().Text("Visual Difference (Red = Differences)").FontSize(14).SemiBold();

                column.Item().PaddingTop(5).Image(_diffImageBytes).FitWidth();

                column.Item().PaddingTop(5).Text(
                    "Interpretation: Red pixels indicate differences between your symbol and the canonical. " +
                    "Black pixels are identical in both images.")
                    .FontSize(9)
                    .Italic()
                    .FontColor(Colors.Grey.Darken1);
            });
        }
    }
}
